### ISSUE TITLE
Potential mislabeling of rows in field 7 in the data block in TsDNADamageCalculator.cc

### ISSUE THREAD

**Issue by n-desjardins** [topas-nbio/TOPAS-nBio-v2.0#11]
Hi, 

From line 697 to line 743 in TsDNADamageCalculator.cc the output of field 7 for the data block is being dealt with. In this file, bases are labelled as row 1 and row 4 while backbones are labelled as row 2 and 3. If I understand well the SDD format, it should be the other way around, that is backbones are rows 1 and 4 and bases are row 2 and 3. 

Field 7 in the data block is defined in page 86 of the "A New Standard DNA Damage (SDD) Data format"

Best,
Nico

**Comment by alebertolet** [comment]
You are actually right. Great catch! I have a different code to read SDD, and, for some reason, I had the bug duplicated, so I didn't catch anything wrong.
I'll update the code shortly. 
Thank you!
