### ISSUE TITLE
CMake trying to include SDD_Reader Twice

### ISSUE THREAD

**Issue by cvelten** [topas-nbio/TOPAS-nBio-v2.0#4]
**Describe the bug**
When running cmake to build TOPAS-nBio the SDD_Reader classes are to be included twice. Once from `root/scorers/SDD_Reader` and once from `root/SDDReader` leading to a cmake error to include the same extension file twice.

```
CMake Error at CMakeHandleExtensions.cmake:51 (message):
  Attempt to add same extension file twice: DrDamageEvent.cc
Call Stack (most recent call first):
  CMakeLists.txt:14 (include)
```

**To Reproduce**
1. TOPAS 3.6.p1
2. TOPAS-nBio v1.0
3. macOS 10.15, clang, cmake 3.20.x

**Expected behavior**
Only provide classes once.

**Comment by jschuemann** [comment]
Sorry, yes, I realized I forgot to add one push, working on that now.

**Comment by jschuemann** [comment]
Should be fixed, please let me know if you still have issues.
