### ISSUE TITLE
Fatal error with TsEmDNAChemistry and no provided BinaryReactions

### ISSUE THREAD

**Issue by cvelten** [topas-nbio/TOPAS-nBio-v2.0#7]
**Describe the bug**
When using `TsEmDNAChemistry` reaction rates are not inherited from G4DNA. Additionally, if no binary reactions are defined for the chemistry, no reaction table is implemented leading to fatal errors in G4Track.

**To Reproduce**
TOPAS 3.7 with TOPAS-nBio (comment the physics modules in/out to switch behavior):
```
s:Ge/World/Material  = "G4_WATER"
d:Ge/World/HLX       = 2.0 mm
d:Ge/World/HLY       = 2.0 mm
d:Ge/World/HLZ       = 2.0 mm
b:Ge/World/Invisible = "True"

s:So/Example/Type                     = "Beam"
s:So/Example/Component                = "BeamPosition"
s:So/Example/BeamParticle             = "e-"
d:So/Example/BeamEnergy               = 1. keV
u:So/Example/BeamEnergySpread         = 0.
s:So/Example/BeamPositionDistribution = "None"
s:So/Example/BeamAngularDistribution  = "None"
i:So/Example/NumberOfHistoriesInRun   = 1

# sv:Ph/Default/Modules = 2 "g4em-dna" "g4em-dna-chemistry"
sv:Ph/Default/Modules = 2 "g4em-dna" "TsEmDNAChemistry"
```

**Expected behavior**
Run in both cases.

**Screenshots / Output**
```
G4WT0 > Begin processing for Run: 0, History: 0
G4WT0 >
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception :
      issued by : G4MolecularInteractionTable::CanReactWith
No reaction table was implemented
*** Fatal Error In Argument *** core dump ***
G4WT0 > G4Track (0x7fbcddaab2a0) - track ID = 2, parent ID = 1
[1]    13644 segmentation fault  ./bin/topas ~/dev/tmp/chemtest.topas
```

**Proposed fix**
1. Derive `TsEmDNAChemistry` from `G4EmDNAChemistry` and call `G4EmDNAChemistry::ConstructReactionTable` before the (re-)setting logic in `TsEmDNAChemistry::ConstructReactionTable`; or
2. Add the standard reaction rates as in the base class and only reset user-defined ones; or
3. Only set user-defined reaction rates and add a `Quit` statement if no reaction rates are defined by the user.

**Comment by jschuemann** [comment]
This has been addressed now by Naoki.
